sudo: required
language: bash 
services: docker
env:
  - DOCKER_IMAGE=php-apache
script:
  - docker build -t ${DOCKER_IMAGE} .
after_script:
  - docker images
  - docker run -d -p 8080:80 -t ${DOCKER_IMAGE}
  - docker ps -a